# Generated by Django 5.2.8 on 2026-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_url',
            field=models.URLField(blank=True),
        ),
    ]
