# Generated by Django 5.2.8 on 2026-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_file_field_to_course_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_type',
            field=models.CharField(blank=True, choices=[('SUBJECTIVE', 'Subjective (Essay/Text)'), ('OBJECTIVE', 'Objective (Code/Math)')], help_text='Set to enable rubric-based AI grading. NULL = legacy grading.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='model_answer_text',
            field=models.TextField(blank=True, default='', help_text='Reference model answer for rubric-based AI grading.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of rubric criteria for AI grading.'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='Test cases for OBJECTIVE code assignments. NULL if not applicable.', null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='submitted_text',
            field=models.TextField(blank=True, default='', help_text='Free-text essay or code content for AI grading.'),
        ),
    ]
