# Generated by Django 5.2.8 on 2026-05-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_assignment_grading_type_assignment_model_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatconversation',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to='main.courseoffering'),
        ),
    ]
