# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_studentsubmission_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/'),
        ),
    ]
