# Generated by Django 5.2.8 on 2026-05-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_assignment_grading_type_assignment_model_answer_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(help_text='Total points awarded by the AI grader.')),
                ('max_score', models.FloatField(help_text='Maximum possible points from the rubric.')),
                ('criteria_breakdown', models.JSONField(default=list, help_text='Per-criteria scoring and justification from the AI.')),
                ('feedback_summary', models.TextField(blank=True, help_text='Overall feedback / summary from the AI grader.')),
                ('raw_llm_response', models.JSONField(blank=True, default=dict, help_text='Raw structured response from the LLM for debugging.')),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_result', to='main.studentsubmission')),
            ],
            options={
                'db_table': 'grading_results',
                'indexes': [models.Index(fields=['submission'], name='grading_res_submiss_909dbd_idx')],
            },
        ),
    ]
